# Builds the local image if it's not present,
# then starts the container
services:
  jlab:
    image: "${image}:${tag}"
    build:
      context: .
      args:
        image: "${image}"
    ports:
      - "8888:8888"
    volumes:
      - ./materials/:/home/jovyan/mounted-files
